// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSyA1xDWqAbrLgZFSyaCr0dhKMTe9SXNE',
    appId: '1:206300820126:web:8c3a1e19c00f780c17418f',
    messagingSenderId: '206300820126',
    projectId: 'ecovidaverde12',
    authDomain: 'ecovidaverde12.firebaseapp.com',
    databaseURL: 'https://ecovidaverde12-default-rtdb.firebaseio.com',
    storageBucket: 'ecovidaverde12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZPZN07AuDOWOIqUCIjUkTfreQIoc8sM',
    appId: '1:206300820126:android:e123d8cd96169a4e17418f',
    messagingSenderId: '206300820126',
    projectId: 'ecovidaverde12',
    databaseURL: 'https://ecovidaverde12-default-rtdb.firebaseio.com',
    storageBucket: 'ecovidaverde12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpIdmXMLnR7tESC2tocy5gTnuOBatjDDw',
    appId: '1:206300820126:ios:9da26c0e7bbb40fe17418f',
    messagingSenderId: '206300820126',
    projectId: 'ecovidaverde12',
    databaseURL: 'https://ecovidaverde12-default-rtdb.firebaseio.com',
    storageBucket: 'ecovidaverde12.appspot.com',
    iosBundleId: 'com.example.ecovidaverde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpIdmXMLnR7tESC2tocy5gTnuOBatjDDw',
    appId: '1:206300820126:ios:9da26c0e7bbb40fe17418f',
    messagingSenderId: '206300820126',
    projectId: 'ecovidaverde12',
    databaseURL: 'https://ecovidaverde12-default-rtdb.firebaseio.com',
    storageBucket: 'ecovidaverde12.appspot.com',
    iosBundleId: 'com.example.ecovidaverde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSyA1xDWqAbrLgZFSyaCr0dhKMTe9SXNE',
    appId: '1:206300820126:web:8c3a1e19c00f780c17418f',
    messagingSenderId: '206300820126',
    projectId: 'ecovidaverde12',
    authDomain: 'ecovidaverde12.firebaseapp.com',
    databaseURL: 'https://ecovidaverde12-default-rtdb.firebaseio.com',
    storageBucket: 'ecovidaverde12.appspot.com',
  );
}
